architect:
  - h1alexbel
docker:
  image: yegor256/rultor-image:1.13.0
assets:
  credentials: l3r8yJ/home#assets/crates-credentials
install: |
  pdd --file=/dev/null
merge:
  script: |
    cargo --color=never test -vv
    cargo --color=never fmt --check
    cargo doc --no-deps
    cargo clippy
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/^version = \"0.0.0\"/version = \"${tag}\"/" Cargo.toml
    sed -i -e "s/0.0.0/${tag}/" src/lib.rs
    cargo --color=never test -vv -- --nocapture
    cargo --color=never fmt --check
    cargo clippy --all-targets --all-features
    git commit -am "${tag}"
    ls -a ../
    mkdir -p ~/.cargo && cp ../credentials ~/.cargo
    cargo --color=never publish