[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fakehub-cli"
path = "src/main.rs"

[dependencies]
clap = "4.5.7"
server = { path = "../server" }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }