get:
  summary: Get a webhook configuration for an app
  description: |-
    Returns the webhook configuration for a GitHub App. For more information about configuring a webhook for your app, see "[Creating a GitHub App](/developers/apps/creating-a-github-app)."
    
    You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
  tags:
    - apps
  operationId: apps/get-webhook-config-for-app
  externalDocs:
    description: API method documentation
    url: https://docs.github.com/rest/apps/webhooks#get-a-webhook-configuration-for-an-app
  responses:
    '200':
      description: Response
      content:
        application/json:
          schema:
            title: Webhook Configuration
            description: Configuration object of the webhook
            type: object
            properties:
              url:
                type: string
                description: The URL to which the payloads will be delivered.
                example: https://example.com/webhook
                format: uri
              content_type:
                type: string
                description: The media type used to serialize the payloads. Supported
                  values include `json` and `form`. The default is `form`.
                example: '"json"'
              secret:
                type: string
                description: If provided, the `secret` will be used as the `key`
                  to generate the HMAC hex digest value for [delivery signature
                  headers](https://docs.github.com/webhooks/event-payloads/#delivery-headers).
                example: '"********"'
              insecure_ssl:
                oneOf:
                  - type: string
                    description: Determines whether the SSL certificate of the host
                      for `url` will be verified when delivering payloads. Supported
                      values include `0` (verification is performed) and `1` (verification
                      is not performed). The default is `0`. **We strongly recommend
                      not setting this to `1` as you are subject to man-in-the-middle
                      and other attacks.**
                    example: '"0"'
                  - type: number
          examples:
            default:
              value:
                content_type: json
                insecure_ssl: '0'
                secret: "********"
                url: https://example.com/webhook
  x-github:
    githubCloudOnly: false
    enabledForGitHubApps: false
    category: apps
    subcategory: webhooks
patch:
  summary: Update a webhook configuration for an app
  description: |-
    Updates the webhook configuration for a GitHub App. For more information about configuring a webhook for your app, see "[Creating a GitHub App](/developers/apps/creating-a-github-app)."
    
    You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
  tags:
    - apps
  operationId: apps/update-webhook-config-for-app
  externalDocs:
    description: API method documentation
    url: https://docs.github.com/rest/apps/webhooks#update-a-webhook-configuration-for-an-app
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            url:
              type: string
            content_type:
              type: string
            secret:
              type: string
            insecure_ssl:
              type: string
        examples:
          default:
            value:
              content_type: json
              insecure_ssl: '0'
              secret: "********"
              url: https://example.com/webhook
  responses:
    '200':
      description: Response
      content:
        application/json:
          schema:
            type: object
#            examples:
#              default:
  x-github:
    githubCloudOnly: false
    enabledForGitHubApps: false
    category: apps
    subcategory: webhooks
