name: cargo
on:
  push:
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  clippy_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
      - run: cargo test --release
      - run: cargo fmt --check